service: lambda-node-dynamo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:139785125919:table/TaskTable
        - arn:aws:dynamodb:us-east-1:139785125919:table/UserTable

plugins:
  - serverless-ignore
  - serverless-offline
functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  addTask:
    handler: src/task.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: src/task.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/task.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  updateTask:
    handler: src/task.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  deleteTask:
    handler: src/task.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete
  addUser:
    handler: src/user.addUser
    events:
      - httpApi:
          path: /users
          method: post
  getUsers:
    handler: src/user.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/user.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get
  updateUser:
    handler: src/user.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/user.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH